- name: Deploy artifact
  hosts: localhost
  tasks:
	- name: Ensure the deployment directory exists
  	file:
    	path: /opt/deploy1
    	state: directory
    	mode: '0777'

	- name: Copy the artifact to the deployment directory
  	copy:
    	src: /var/lib/jenkins/workspace/mvn5/target/HelloMaven-1.0-SNAPSHOT.jar  # Replace with actual file
    	dest: /opt/deploy1/likitha.jar
